parameters:
  lcn.image_uploader.allowed_extensions:
    - gif #image/gif
    - png #image/png
    - jpg #image/jpeg
    - jpeg #image/jpeg

  lcn.image_uploader.galleries:
    # define your own named galleries here
    # The following "demo" gallery is just an example.
    # For advanced image resizing and optimization, you can optionally configure an image proxy.
    demo: #this is the gallery name
      max_number_of_files: 5
      max_file_size: null #max file size in bytes. if set to null or omitted, system settings (e.g. php.ini) will be used
      sizes:
        # required: "thumbnail" - used to display thumbnails ín upload widget
        thumbnail:
          folder: thumbnail
          max_width: 200
          max_height: 150
          crop: true
          proxy:
            enabled: %lcn_file_uploader.image_proxy_enabled%
            url: https://my-source.imgix.com~imageUrl~
            parameters:
              w: ~max_width~
              h: ~max_height~
              fit: crop
              crop: faces

        # required: "original" - used to store "original" versions of files (resamples images if needed)
        original:
          folder: original
          max_width: 2000
          max_height: 1125
          crop: false
          proxy:
            enabled: %lcn_file_uploader.image_proxy_enabled%
            url: https://my-source.imgix.com~imageUrl~
            parameters:
              w: ~max_width~
              h: ~max_height~
              fit: clip

        # optional: define any additional image size you need.
        # You can set the folder setting to null (or omit it entirely) if you are using an image proxy and
        # do not want to store the resized images locally
        standard:
          folder: standard
          max_width: 600
          max_height: 400
          crop: true
          proxy:
            enabled: %lcn_file_uploader.image_proxy_enabled%
            url: https://my-source.imgix.com~imageUrl~
            parameters:
              w: 600
              h: 400
              fit: crop
              crop: faces


services:

    lcn.image_uploader:
        class: Lcn\ImageUploaderBundle\Service\ImageUploader
        arguments: [@service_container, %lcn.image_uploader.galleries%, %lcn.image_uploader.allowed_extensions%]

    lcn.image_uploader.twig_extension:
        class: Lcn\ImageUploaderBundle\Twig\ImageUploaderExtension
        arguments: [@lcn.image_uploader]
        tags:
            - { name: twig.extension }

    lcn.image_uploader.image_gallery.remove_listener:
            class: Lcn\ImageUploaderBundle\Listener\ImageGalleryEntityEventListener
            arguments: [@lcn.image_uploader]
            tags:
                - { name: doctrine.event_listener, event: preRemove }